# NumPy Mathematical Functions
https://www.youtube.com/watch?v=PhEsZGkTx5s&ab_channel=VinothRathinam

In [1]:
import numpy as np

In [2]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [4]:
np.sin(8)

0.9893582466233818

In [5]:
np.cos(x)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [6]:
np.tan(x)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [7]:
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [8]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [9]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [10]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [11]:
np.square(x)

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
b = np.linspace(1,10,20)

In [13]:
b

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [14]:
np.around(b,decimals=2)

array([ 1.  ,  1.47,  1.95,  2.42,  2.89,  3.37,  3.84,  4.32,  4.79,
        5.26,  5.74,  6.21,  6.68,  7.16,  7.63,  8.11,  8.58,  9.05,
        9.53, 10.  ])

In [15]:
np.around(b,decimals=-2)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [16]:
np.floor(b)

array([ 1.,  1.,  1.,  2.,  2.,  3.,  3.,  4.,  4.,  5.,  5.,  6.,  6.,
        7.,  7.,  8.,  8.,  9.,  9., 10.])

In [17]:
np.ceil(b)

array([ 1.,  2.,  2.,  3.,  3.,  4.,  4.,  5.,  5.,  6.,  6.,  7.,  7.,
        8.,  8.,  9.,  9., 10., 10., 10.])

In [18]:
np.round(b)

array([ 1.,  1.,  2.,  2.,  3.,  3.,  4.,  4.,  5.,  5.,  6.,  6.,  7.,
        7.,  8.,  8.,  9.,  9., 10., 10.])

In [19]:
np.round(2.5)

2.0

# Numpy statistical functions
https://www.youtube.com/watch?v=9s-WRIg24AQ&ab_channel=jyostnabodapati

**in 2D array**
- axis 0 - column
- axis 1 - row

In [20]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.sum(a)

45

In [23]:
np.sum(a,axis=0)

array([12, 15, 18])

In [24]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [25]:
# max value in array

In [26]:
np.amax(a)

9

In [27]:
np.amax(a,axis=0)

array([7, 8, 9])

In [28]:
np.amax(a,axis=1)

array([3, 6, 9])

In [29]:
# mean value

In [30]:
np.mean(a)

5.0

In [31]:
np.mean(a,axis=0)

array([4., 5., 6.])

In [32]:
np.mean(a,axis=1)

array([2., 5., 8.])

In [33]:
# std deviation of array

In [34]:
np.std(a)

2.581988897471611

In [35]:
np.std(a,axis=0) #coulmn

array([2.44948974, 2.44948974, 2.44948974])

In [36]:
np.std(a,axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [37]:
# varience in array

In [38]:
np.var(a)

6.666666666666667

In [39]:
np.var(a,axis=0) #coulmn

array([6., 6., 6.])

In [40]:
np.var(a,axis=1)

array([0.66666667, 0.66666667, 0.66666667])

In [41]:
np.average(a)

5.0

In [42]:
wt = [[1,2,3],[4,5,6],[7,8,9]]

In [43]:
np.average(a, weights=wt)

6.333333333333333

In [44]:
#30th percentile
np.percentile(a,30)

3.4

In [45]:
np.percentile(a,30,axis=0)

array([2.8, 3.8, 4.8])

In [46]:
np.percentile(a,30,axis=1)

array([1.6, 4.6, 7.6])

In [47]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
## difference b/w peek to peek values

In [49]:
np.ptp(a)

8

In [50]:
np.ptp(a,axis=0)

array([6, 6, 6])

In [51]:
np.ptp(a,axis=1)

array([2, 2, 2])

# NumPy Sorting and Searching

In [52]:
a = np.random.randint(1,9,8).reshape(2,4)
a

array([[1, 8, 4, 2],
       [6, 8, 4, 5]])

In [53]:
np.sort(a)

array([[1, 2, 4, 8],
       [4, 5, 6, 8]])

In [54]:
b = np.random.randint(1,9,8)
b

array([4, 6, 6, 7, 1, 1, 3, 2])

In [55]:
np.sort(b)

array([1, 1, 2, 3, 4, 6, 6, 7])

In [56]:
np.sort(a,axis=0)

array([[1, 8, 4, 2],
       [6, 8, 4, 5]])

In [57]:
np.sort(a,axis=1)

array([[1, 2, 4, 8],
       [4, 5, 6, 8]])

In [58]:
np.sort(a,axis=None)

array([1, 2, 4, 4, 5, 6, 8, 8])

In [59]:
b

array([4, 6, 6, 7, 1, 1, 3, 2])

In [60]:
sort_idx=np.argsort(b)
sort_idx

array([4, 5, 7, 6, 0, 1, 2, 3])

In [61]:
b[sort_idx]

array([1, 1, 2, 3, 4, 6, 6, 7])

In [62]:
b[sort_idx[::-1]]

array([7, 6, 6, 4, 3, 2, 1, 1])

In [63]:
a = np.array(['a','b','c','d','e'])  
  
b = np.array([12, 90, 380, 12, 211])  

In [64]:
(a,b)

(array(['a', 'b', 'c', 'd', 'e'], dtype='<U1'),
 array([ 12,  90, 380,  12, 211]))

In [65]:
idx = np.lexsort((a,b))
idx

array([0, 3, 1, 4, 2])

In [66]:
for id in idx:
    print(a[id],b[id])

a 12
d 12
b 90
e 211
c 380


In [67]:
# This function is used to find the location of the non-zero elements from the array.
b = np.array([12, 0, 380, 12, 211])  
idx = np.nonzero(b)
idx

(array([0, 2, 3, 4]),)

In [68]:
b[idx]

array([ 12, 380,  12, 211])

In [69]:
np.where(b>50)

(array([2, 4]),)

In [70]:
b>50

array([False, False,  True, False,  True])

# NumPy Copies and Views

In [71]:
b

array([ 12,   0, 380,  12, 211])

In [72]:
bb = b.view()

In [73]:
b.view(dtype=np.int8)

array([ 12,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0, 124,   1,   0,   0,   0,   0,   0,   0,  12,   0,
         0,   0,   0,   0,   0,   0, -45,   0,   0,   0,   0,   0,   0,
         0], dtype=int8)

In [74]:
bb[1] = 77

In [75]:
bb

array([ 12,  77, 380,  12, 211])

In [76]:
b

array([ 12,  77, 380,  12, 211])

In [80]:
bc = b.copy()
bc[1] = 99

In [81]:
bc

array([ 12,  99, 380,  12, 211])

In [82]:
b

array([ 12,  77, 380,  12, 211])

In [89]:
b = a.view()  
  
b.shape = 4,3;  
 
b[0][2] = 777

print("\nOriginal array \n",a)  
print("\nview\n",b)  



Original array 
 [[  1   2 777   4]
 [  9   0   2   3]
 [  1   2   3  19]]

view
 [[  1   2 777]
 [  4   9   0]
 [  2   3   1]
 [  2   3  19]]


# NumPy Matrix Library